import type { LucideIcon } from 'lucide-react'
import {
  Home, Search, User, Users, Settings, Bell, Star, Bookmark, Flag, Tag,
  BarChart2, LineChart, PieChart, TrendingUp, Activity,
  ShoppingCart, Package, Truck, Warehouse, Box, DollarSign, CreditCard,
  Phone, Mail, Globe, MapPin, Navigation,
  Shield, Lock, Key, Eye,
  Zap, Cpu, Database, Server, Code, Terminal, Wifi,
  Image, Video, Music, Mic, Camera,
  Calendar, Clock, Timer,
  Layers, Grid, List, Table, Layout, LayoutDashboard,
  Edit, Trash2, Copy, Save, Upload, Download, RefreshCw,
  Link, Share2, ExternalLink,
  Info, AlertTriangle, AlertCircle, HelpCircle, CheckCircle, XCircle,
  Briefcase, Building2, Building,
  MessageCircle, MessageSquare,
  FileText, File, Folder, FolderOpen, Book, BookOpen,
  ArrowRight, ArrowLeft, ChevronRight, ChevronDown,
  Award, Gift, Smile, Heart,
  UserPlus, UserMinus, LogIn, LogOut,
  Sliders, ToggleLeft, Sun, Moon,
  Filter, SortAsc, SortDesc,
  Printer, Clipboard, Archive, Inbox,
  Map, Compass, Target, Crosshair,
} from 'lucide-react'

export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  // Navigation & UI
  home:            Home,
  search:          Search,
  settings:        Settings,
  bell:            Bell,
  filter:          Filter,
  'sort-asc':      SortAsc,
  'sort-desc':     SortDesc,
  layout:          Layout,
  dashboard:       LayoutDashboard,
  layers:          Layers,
  grid:            Grid,
  list:            List,
  table:           Table,
  sliders:         Sliders,
  toggle:          ToggleLeft,
  // Users & Auth
  user:            User,
  users:           Users,
  'user-plus':     UserPlus,
  'user-minus':    UserMinus,
  'log-in':        LogIn,
  'log-out':       LogOut,
  shield:          Shield,
  lock:            Lock,
  key:             Key,
  eye:             Eye,
  // Communication
  mail:            Mail,
  phone:           Phone,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  bell2:           Bell,
  // Files & Docs
  file:            File,
  'file-text':     FileText,
  folder:          Folder,
  'folder-open':   FolderOpen,
  book:            Book,
  'book-open':     BookOpen,
  clipboard:       Clipboard,
  archive:         Archive,
  inbox:           Inbox,
  printer:         Printer,
  // Commerce & Finance
  'shopping-cart': ShoppingCart,
  package:         Package,
  truck:           Truck,
  warehouse:       Warehouse,
  box:             Box,
  'dollar-sign':   DollarSign,
  'credit-card':   CreditCard,
  // Analytics
  'bar-chart':     BarChart2,
  'line-chart':    LineChart,
  'pie-chart':     PieChart,
  'trending-up':   TrendingUp,
  activity:        Activity,
  // Location
  globe:           Globe,
  'map-pin':       MapPin,
  navigation:      Navigation,
  map:             Map,
  compass:         Compass,
  target:          Target,
  crosshair:       Crosshair,
  // Tech
  zap:             Zap,
  cpu:             Cpu,
  database:        Database,
  server:          Server,
  code:            Code,
  terminal:        Terminal,
  wifi:            Wifi,
  // Media
  image:           Image,
  video:           Video,
  music:           Music,
  mic:             Mic,
  camera:          Camera,
  // Time
  calendar:        Calendar,
  clock:           Clock,
  timer:           Timer,
  // Actions
  edit:            Edit,
  trash:           Trash2,
  copy:            Copy,
  save:            Save,
  upload:          Upload,
  download:        Download,
  refresh:         RefreshCw,
  link:            Link,
  share:           Share2,
  'external-link': ExternalLink,
  // Status & Feedback
  info:            Info,
  warning:         AlertTriangle,
  error:           AlertCircle,
  help:            HelpCircle,
  'check-circle':  CheckCircle,
  'x-circle':      XCircle,
  // Business
  briefcase:       Briefcase,
  building:        Building,
  office:          Building2,
  // Misc
  star:            Star,
  heart:           Heart,
  bookmark:        Bookmark,
  flag:            Flag,
  tag:             Tag,
  award:           Award,
  gift:            Gift,
  smile:           Smile,
  sun:             Sun,
  moon:            Moon,
  'arrow-right':   ArrowRight,
  'arrow-left':    ArrowLeft,
  'chevron-right': ChevronRight,
  'chevron-down':  ChevronDown,
}

export const LUCIDE_ICON_NAMES = Object.keys(LUCIDE_ICON_MAP)

export function lucideDisplayName(name: string): string {
  return name.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())
}
